name: Android CI main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup secrets shh
      env:
        gs: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo gs > app/google-services.json
      
    - name: Build with Gradle
      run: ./gradlew build -P isCI=true
